# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
	before_all do
		ENV["SLACK_URL"]="https://hooks.slack.com/services/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"
	end
	desc "Deploy a new version to the google play"
	lane :deploy do
		gradle(
			task: "clean assembleRelease"
		)
	end

	after_all do |lane|
		slack(
			message: "successfuly deployed"
		)
	end

	error do |lane, exception|
		slack(
			message: exception.message,
			success: false
		)
	end

end
